### ISSUE TITLE
Not booting after installation

### ISSUE THREAD

**Issue by Roshaanv** [gnodipac886/MatebookXPro-hackintosh#100]
Hello guys

I installed macOS catalina with an external ssd (tried it with gibmacOs and with a macOS VM) on my main drive (Liteon), but if I try to boot, the apple logo and the bar shows up, it gets filled out to about 90% and it crahes. After the crash, it reboots and shows an error screen saying "Your computer restarted because of a problem (...)"

I've been trying it for the past 3 days, havent found a solution yet. Any thoughts?

**Comment by ED1FF** [comment]
@Roshaanv Hi, not sure we have same issue.
Please check your debug logs. If you have same looping message as on image below. You can try to add flag -disablegfxfirmware to your config.plist.

https://user-images.githubusercontent.com/55004532/64463119-278a6880-d103-11e9-94ac-dad096fdcfc6.jpg
![image](https://user-images.githubusercontent.com/26602353/78421253-e1789180-765e-11ea-91fb-035007193661.png)

**Comment by Roshaanv** [comment]
> @Roshaanv Hi, not sure we have same issue.
> Please check your debug logs. If you have same looping message as on image below. You can try to add flag -disablegfxfirmware to your config.plist.
> 
> https://user-images.githubusercontent.com/55004532/64463119-278a6880-d103-11e9-94ac-dad096fdcfc6.jpg
> ![image](https://user-images.githubusercontent.com/26602353/78421253-e1789180-765e-11ea-91fb-035007193661.png)

Thank you for the response!
Where do I find the debug logs?
