### ISSUE TITLE
Found legacy AptioMemoryFix Driver and network required

### ISSUE THREAD

**Issue by Tarvald** [gnodipac886/MatebookXPro-hackintosh#102]
Hi,
I created bootable pendrive following instructions.
However, I cannot boot installation because I just have "Found legacy AptioMemoryFix Driver" error in the top left corner of screen and then black screen, nothing happend.
However, when I completly replace clover by another configuration, it works, but installator require internet connection to continue instalataion.
Can I somehow skip network requirement? bacouse as you know matebook does not have ethernet port.
Thanks a lot!

**Comment by gnodipac886** [comment]
Are you using my USB files? If it doesn't work, just update the clover
