### ISSUE TITLE
Bluethooth is it working?

### ISSUE THREAD

**Issue by Tarvald** [gnodipac886/MatebookXPro-hackintosh#103]
Hi guys,
Do you have working bluetooth on your setup?
I have first version of Matebook x pro and Hackintosh does not see bluetooth at all.

Thanks a lot!

**Comment by Roshaanv** [comment]
I have the 2018 Matebook X Pro and it works for me

**Comment by Chatbox1024** [comment]
> I have the 2018 Matebook X Pro and it works for me

Which version of the IntelBluetoothFirmware kext are you using?  v1.0.3 is the latest, but I haven't tried that yet.  I, however, tried with v1.0.2...but it was not stable, and also buggy.

**Comment by Roshaanv** [comment]
> > I have the 2018 Matebook X Pro and it works for me
> 
> Which version of the IntelBluetoothFirmware kext are you using? v1.0.3 is the latest, but I haven't tried that yet. I, however, tried with v1.0.2...but it was not stable, and also buggy.

I am using v1.0.2 right now. Sometimes Bluetooth is not available and I have to restart to get it back working again, but that doesn't occur often.

**Comment by androidek** [comment]
I'm using v1.0.3 and Bluetooth works fine - I never had to restart the device to access it. However, some peripherals don't work - I cannot enable my wireless mouse to work :(, but it might be the mouse issue; I need to test it with Macbook to check it

**Comment by PLTorrent** [comment]
I have 1.0.1 on Mach-WX9 (Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, 8GB, no dGPU) and BT seems to be working fine and stable.
