### ISSUE TITLE
Wireless Sidecar?

### ISSUE THREAD

**Issue by kilgil27** [gnodipac886/MatebookXPro-hackintosh#104]
Is it possible to get sidecar working wirelessly? I have it working wired, but I cannot see my iPad when I try to connect wirelessly. I also am unable to open AirDrop, not sure if the two things are related

**Comment by DanteSung** [comment]
You need a Qualcomm Network card to enable these two things. The pre-installed Intel network card does not support either of these functions

**Comment by gnodipac886** [comment]
It can be possible, but the kext authors would need to implement this, would take a long time.
