### ISSUE TITLE
Ethernet not working in MacOS Utilities

### ISSUE THREAD

**Issue by therealmrsymba** [gnodipac886/MatebookXPro-hackintosh#110]
I am a newbie to all of this and I have been researching the entire weekend but I cannot get the Ethernet working? I have used 3 different Ethernet adapters and tried to use the hotspot on my phone and nothing works. I do not have a MacBook so I have followed the guide for Windows using my Matebook X Pro. I have tried using 5092 and 5103 and neither of them detect any of the many adapters that I have used. I have to be missing something somewhere.

**Comment by JonnIEnglish** [comment]
Hi Mr Symba

Do you have a wifi USB adapter? I have the TP-Link TL-WN725N which requires one to download the drivers from the TP-link website first and then install them on your Hackintosh before being able to connect to the internet. Also I have found that it only works in the USB-A port on the right of the Matebook x Pro and not through any USB-C adapters.

**Comment by therealmrsymba** [comment]
Hi JonnIEnglish,

I did purchase one of those as well. It is an Asus AC1200 (USB-AC53 Nano) and it shows up under network utility but there’s no option on the top right for me to select a wireless network to connect to; so I’m stuck trying to get connected so that I can download MacOS for install.

**Comment by JonnIEnglish** [comment]
Okay, that's odd. Another method I have used to get my hackintosh connected is Bluetooth tethering. You can connect to a wifi network on your phone and then turn on bluetooth on both your phone and Matebook, in the bluetooth utility in MacOS click connect on your phone once it is found and let them pair. Once paired you can go to Setting > connection and sharing  and turn on bluetooth tethering. This should allow your Matebook to connect to the internet so you can download what you need.

**Comment by therealmrsymba** [comment]
Hey Johnni, 

Did you resolved your issues with the Bluetooth and random shutdowns ?

**Comment by JonnIEnglish** [comment]
Hey, yeah I actually did. Everything is working very smoothly at the moment except for the occasional kernel panic during sleep.

**Comment by therealmrsymba** [comment]
Are you running Catalina or Mojave? I keep having issues with Bluetooth disconnecting, sleeping and rebooting. I’ll mess around with it. Also do you have airdrop?

**Comment by JonnIEnglish** [comment]
I am running Catalina. That's odd that the bluetooth is doing that. Mine never really had any issues. I will attach my Clover folder and maybe you can try and temporarily boot off it and see if bluetooth works with it. Or otherwise post your Paste your Clover folder here and I can have a look at it. In terms of airdrop, I don't have any other Apple devices to test it with so I have no way of knowing if it works. 
[CLOVER.zip](https://github.com/gnodipac886/MatebookXPro-hackintosh/files/4593777/CLOVER.zip)

**Comment by therealmrsymba** [comment]
Okay cool sounds good. I’ll test it tonight. I’m using Mojave because I can’t get Catalina to install for some reason but I’ll give it a shot

**Comment by JonnIEnglish** [comment]
Oh, how did you create your boot disk? I used the unibeast method and it worked very smoothly with the Catalina instillation.

**Comment by therealmrsymba** [comment]
I haven’t tried unibeast and not even sure how it works. I am very new to this.

**Comment by JonnIEnglish** [comment]
Yeah I am also quite new to it. Only about 5 weeks in. What are you having trouble with, with unibeast?

**Comment by therealmrsymba** [comment]
Yeah I’m like maybe a week old to this. I don’t even know what Unibeast is. I’ve seen it looking through things but didn’t know what I did. I just started learning how to use Clover Config

**Comment by JonnIEnglish** [comment]
Just follow a tutorial like this one. https://www.youtube.com/watch?v=9naDucGj0h0

**Comment by therealmrsymba** [comment]
Thanks for the info. I haven’t looked at this tutorial yet but I did get it working last night with your help. I installed on a separate SSD instead of my internal and it was seamless.

**Comment by JonnIEnglish** [comment]
Good to hear, well done! It's also worth remembering that MacOS doesn't install properly on the Samsung SSD that comes with the Matebook x pro 2018. (And I'm not sure about the later models).

**Comment by therealmrsymba** [comment]
Thank you! I really appreciate your help. Now I am going to experiment with mounting the SSD to my device.
