### ISSUE TITLE
performance of igpu(can not stick on 1.1 Ghz)

### ISSUE THREAD

**Issue by kxlv2000** [gnodipac886/MatebookXPro-hackintosh#112]
Recently i found that the performance of my igpu(UHD 620) on macOS is far away from windows, the openCL result is about 3500 on macOS, while on windows it is 5500.
 the frequency of IGPU is about 300mhz-800mhz and can not stick on 1.1Ghz.
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/49295281/82720120-20cc7180-9ce3-11ea-8808-99e92cddb9f0.png">
However, I find a way to fix this problem by re-make the CPUFriendDataProvider.kext, and put them in L/E, this may make difference sometimes and the openCL result comes to 4500, the UI of macOS become much more smooth. but usually it makes no difference, which is really confusing.
so I guess there is something wrong with the load order of DSDT and kext, 
finally when I saw the source code of DSDT, i found that there are lot of mistake that doesn't match my 8250U, and UHD 620, which may block the performance of IGPU, the reason why sometimes CPUFriend can fix this problem maybe it was loaded after the DSDT, and overwrite the wrong cpu info, and take effort. 
I still haven't find an easy way to fix this problem totally. But I have two idea, first change to open core platform and customs the load order of kext and dsdt, second re-write the dsdt source code. but both of them are too hard to me.
Are you facing this problem, too. Do you have a better idea, please comment here, thanks.

**Comment by profzei** [comment]
Hi, I don't know if my [config](https://github.com/profzei/Matebook-X-Pro-2018) is affected by the same issue... or not: I changed completely the corresponding framebuffer injection for UHD620. Please, if you want, try it and let me know: afaik during clover (or open core) bootloading process DSDT.aml is always loaded before any other SSD. So I'm curious about your feedback!

**Comment by kxlv2000** [comment]
> Hi, I don't know if my [config](https://github.com/profzei/Matebook-X-Pro-2018) is affected by the same issue... or not: I changed completely the corresponding framebuffer injection for UHD620. Please, if you want, try it and let me know: afaik during clover (or open core) bootloading process DSDT.aml is always loaded before any other SSD. So I'm curious about your feedback!

Can you see your GFX AVG frequency in IPG? before I changing the frame buffer ig-platform-id to 00001B59  and device-id  to 16590000, and model name to "Intel UHD Graphics 620", I can't see the frequency in IPG!
If you are worry about the performance of IGPU was blocked,Just run GeekBench 5 openCL test check if the IGPU frequency is stick on 1.1Ghz,here is my best score that I can got now. However still far away from windows score 5500...
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/49295281/82732272-c3660e00-9d3e-11ea-9882-9c163c1401f1.png">
or you can try final cut to see the frequency. here is my ideal state of IGPU.
<img width="406" alt="image" src="https://user-images.githubusercontent.com/49295281/82732399-89493c00-9d3f-11ea-8558-396e2f5003d5.png">
curious about your GeekBench 5 OpenCL result. please let me know on your convenience, thanks!

**Comment by profzei** [comment]
It's my first benchmark! I don't know if it is relevant for UHD620 OpenCL test but my Matebook has an i7-8550U CPU.
Here are my results:
<img width="1500" alt="Screenshot 2020-05-23 at 19 33 27" src="https://user-images.githubusercontent.com/47076961/82736847-d374f200-9d2c-11ea-9fec-4a1214a909c3.png">
<img width="1500" alt="Screenshot 2020-05-23 at 19 34 37" src="https://user-images.githubusercontent.com/47076961/82736857-e2f43b00-9d2c-11ea-9d52-b7a27e47f92f.png">

**Comment by kxlv2000** [comment]
Hi, your OpenCL score seems has no problem, I looked up some material which said It is normal that OpenCL efficient on macOS is lower than windows, and the real performance may have no difference, actually.

I also tried your config, but if I clone all of your clover folder directly into my EFI, the IGPU seems cannot load correctly.
![61362491BF5B88F56763E52F74570052](https://user-images.githubusercontent.com/49295281/82744691-82a5dd80-9dae-11ea-82a3-1721956ab3fd.png)
however, If I copy your plist, kext, and ACPI folder, It boot correctly and the IGPU seems much more stable, here are my newest score:
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/49295281/82744569-f941db80-9dac-11ea-964b-e08b186eefc8.png">

I'll keep trying your config to check wether it can work properly after some reboot(my previous ones can't),and give you feedback, Thanks for your kindness very much, It takes hope after 1 mouth work without any outcomes.

**Comment by kxlv2000** [comment]
> Hi, I don't know if my [config](https://github.com/profzei/Matebook-X-Pro-2018) is affected by the same issue... or not: I changed completely the corresponding framebuffer injection for UHD620. Please, if you want, try it and let me know: afaik during clover (or open core) bootloading process DSDT.aml is always loaded before any other SSD. So I'm curious about your feedback!

I still have a little question, have you ever consider about unlock CPU&IGPU 's TDP limit? because the CPU & IGPU share the same power limit PL1=15w PL2=29w, so it cause the limitation of performance when temperature is not high, as you can see in this screenshot, the IGPU cost much power and limited CPU's frequency a lot. 
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/49295281/82745159-c3ecbc00-9db3-11ea-9079-88ca6f122173.png">
in windows we can simply use intel XTU, on macOS I have tried voltageShift.kext, decrease voltage do make my MBXP cooler, but performance can not be better in such a 15w power limit. voltageShift.kext can not unlock HUAWEI's costumes mouther board TDP limit, if you can unlock TDP by DSDT or CPUFriendDataProvider, maybe you can try this performance improvement for free in a cool environments?

**Comment by profzei** [comment]
I didn't try yet to undersold my machine with the use of voltageShift.kext...
I don't know whether it could be advisable to "unlock" tdp since it's an ultrabook, but I can try...

**Comment by kxlv2000** [comment]
Hi, after some reboots using your config, I found my IGPU frequency sometimes still cannot reach 1.1Ghz, and the pkg power can hardly goes over 15w. I still can't find the key point that determines the limits of IGPU's frequency (even though I didn't change any config between the  boot with High Performance and a boot with poor performance...

the problem still needs to be solve...
