### ISSUE TITLE
Installation stuck because of operating problem

### ISSUE THREAD

**Issue by RoderickQiu** [gnodipac886/MatebookXPro-hackintosh#13]
I cannot install it on my Matebook X Pro 2018, because I cannot use trackpad and bluetooth mouse during the installation. I've already reached the installation page, and I've settled the disk. But the disk-selecting method of installation is unable to use keyboard to control, so I cannot go any further...

Is there a way out?

I could call everything including log panel, but I cannot select my disk to start installation...

**Comment by gnodipac886** [comment]
Can you find a wired mouse? Just connect it via USB, get a USB C to USB dongle.

**Comment by RoderickQiu** [comment]
I thought I had one, but cannot find...

**Comment by RoderickQiu** [comment]
And there is a mistake in readme: it's NVidia GeForce MX150 but no GTX.

**Comment by RoderickQiu** [comment]
The June 1 update seems to be useless for this problem. Is there a way I can just use my trackpad in installation? Because after installment, Its said that we can use trackpad,

**Comment by gnodipac886** [comment]
I currently don't have a solution for that... Though you can try rebooting from Windows for bluetooth.

**Comment by RoderickQiu** [comment]
OK I'll try to find a mouse later.
