### ISSUE TITLE
No trackpad after June update

### ISSUE THREAD

**Issue by kilgil27** [gnodipac886/MatebookXPro-hackintosh#16]
After installing the June update with the autoinstaller, my trackpad is no longer working. I also do not have the option to turn bluetooth on/off. Maybe it did not install correctly? This is what I see when I run the autoinstaller

https://i.imgur.com/yYw2OZg.png

**Comment by Talal916** [comment]
Are you sure you loaded the kexts correctly? My trackpad and bluetooth on/off is working.

**Comment by kilgil27** [comment]
I copied the kexts from the latest CLOVER folder downloaded from github into the EFI mount and rebooted, I am now able to turn bluetooth on and off, but still no trackpad

**Comment by gnodipac886** [comment]
sh -c "$(curl -fsSL https://raw.githubusercontent.com/gnodipac886/MatebookXPro-hackintosh/master/onekey_installer.sh)"

Try running this in terminal directly, it should download the files and run the autoinstaller script. I’ve tried it multiple times already.

**Comment by kilgil27** [comment]
i get the following error:

--| Downloading GitHub files into Downloads folder |--
------------------------------------------------------
######################################################################## 100.0%
curl: (3) <url> malformed
ERROR: Fail to download GitHub Files, please check your Internet connection!

**Comment by kilgil27** [comment]
nvm, re-downloaded the zip and ran again, now working. Thanks!
