### ISSUE TITLE
Occasionally, on wake from sleep, trackpad doesn't work. 

### ISSUE THREAD

**Issue by Talal916** [gnodipac886/MatebookXPro-hackintosh#18]
Doesn't happen on every wake, just occasionally. Any way to track this?

**Comment by gnodipac886** [comment]
are you using the keyboard by any chance?

The trackpad is disabled when you are using the keyboard

**Comment by Talal916** [comment]
Nope, just not working at all. Whether the keyboard is in use or not.

**Comment by gnodipac886** [comment]
Maybe try downloading the newest version of this https://github.com/alexandred/VoodooI2C/releases and replace it.

**Comment by Talal916** [comment]
Copy all of those kexts in ?

**Comment by gnodipac886** [comment]
yep
