### ISSUE TITLE
BrcmFirmwareRepo.kext

### ISSUE THREAD

**Issue by khant14** [gnodipac886/MatebookXPro-hackintosh#19]
The readme mentions a BrcmFirmwareRepo.kext in the repo, but it is not there. It's found in a older commit though: https://github.com/gnodipac886/MatebookXPro-hackintosh/tree/8ec6263ae05a3ecfa6bac89591d557aac9722369/CLOVER/kexts/Other

> IMPORTANT BrcmFirmwareRepo.kext is in /CLOVER/kexts/Other from this repository - make sure to move it to /Library/Extensions. These kexts will allow bluetooth to persist after a single reboot from Windows.

**Comment by gnodipac886** [comment]
We've found a better way to do bluetooth, I will update soon.
