### ISSUE TITLE
Tunnel WiFi adapter from VM

### ISSUE THREAD

**Issue by khant14** [gnodipac886/MatebookXPro-hackintosh#22]
Is there a way to attach the wifi card into a VM and then tunnel the network back to the host machine? With a lightweight VM, it's like essentially having wifi.

With bluetooth, you can load the firmware/device by loading a VM. Is there a way to attach the wifi/network adapter to a VM? I haven't been able to get any VM to see that there is even a wifi adapter in the system.

**Comment by gnodipac886** [comment]
yea... I also had thoughts like that, like a network bridge, but the thing is just that it doesn't recognize the card... its on my to do list, but it'll be great if you could also help! :)
