### ISSUE TITLE
Bluetooth Issues

### ISSUE THREAD

**Issue by byronpc** [gnodipac886/MatebookXPro-hackintosh#23]
Hi, I'm trying to follow the instructions on the windows only guide

> e. Locate your USB in the left sidebar and navigate to OS X Base System/Install macOS Mojave.app/Contents
f. Right-click in the empty space in the main window and select Copy Here g. Navigate to Install macOS Mojave.app\Contents and select the SharedSupport folder h. This should start copying the folder to your USB - this might take a while to complete.

What exactly does this mean? The USB already has SharedSupport folder in the **Install macOS Mojave.app/Contents** folder

**Comment by byronpc** [comment]
Hi, so I managed to boot the mac installer however i'm running into issues installing it.

One of the images i used which was a `10.14.4` stops at 2 minutes left with the message `install fails at verifying installesd.dmg`

On another `10.14.1` version provided by Shaneee (WINDOWS guide), I get a `verification of file failed at chunk 1`

I'm using the windows guide. I've also copied the clover directory from your repo to the clover partition on my usb.

**Comment by byronpc** [comment]
managed to make it work using another image

https://drive.google.com/open?id=1leeIszys4k_njCghWbVebzzMvNfYvhC1

**Comment by byronpc** [comment]
I'm trying to fix now is Bluetooth.

When I boot off clover from my USB, it works. But when I boot of clover on my SSD, it's not available.

1. I've already tried rebooting from Windows (not exactly sure what this does)
2. I didn't find `BrcmFirmwareRepo.kext` from your repo but I got one from https://bitbucket.org/RehabMan/os-x-brcmpatchram/downloads/

I placed it under /Library/Extensions but still not working. Any ideas?

**Comment by RoderickQiu** [comment]
I thought the BrcmFirmwareRepo.kext has been in trash since a former update, and a new way has came out in the 7.1 update.
You can see #19.

**Comment by RoderickQiu** [comment]
> 
> 
> Hi, so I managed to boot the mac installer however i'm running into issues installing it.
> 
> One of the images i used which was a `10.14.1` by Shanee (windows guide) stops at 2 minutes left with the message `install fails at verifying installesd.dmg`
> 
> On another `10.14.0` version , I get a `verification of file failed at chunk 1`
> 
> I'm using the windows guide. I've also copied the clover directory from your repo to the clover partition on my usb.

Different pieces of things work for just different people - sometimes things are just funny. 

I used a dmg from pcbeta and it was just fantastic.

**Comment by byronpc** [comment]
I tried the new solution you provided with regards to bluetooth but it doesn't seem to be working for me unfortunately. After unchecking the `share bluetooth` and checking the `intel bluetooth` box from the vm's settings. the bluetooth icon on the upper right still says not available. Any ideas?

**Comment by gnodipac886** [comment]
You have to check the intel, then uncheck it after 4-5 seconds.

**Comment by byronpc** [comment]
and also do we have issues with pairing bluetooth LE devices? just wondering..

**Comment by gnodipac886** [comment]
Actually, in system preferences, it shows that it is supported.
You can try on your own too.

**Comment by byronpc** [comment]
yep having a hard time pairing my mx master 2s. so i'm not sure if it's logitech's fault or hackintosh 😄

**Comment by kilgil27** [comment]
I can't seem to pair any Logitech mice with MacOS

**Comment by Talal916** [comment]
I couldn't pair my 2S either. Just use the receiver

**Comment by kilgil27** [comment]
but what about my usb wifi?

**Comment by gnodipac886** [comment]
What about your USB wifi?

**Comment by yamsboi** [comment]
@byronpc i could not pair my MX Master, not sure why because my QC35 II works fine

**Comment by kilgil27** [comment]
Well there's only 1 USB A port so unless I'm using a hub/adapter, I can only have one plugged in at a time.

But has anyone had luck pairing any bluetooth mice at all? I've tried 3 different ones, and they all seem to not work. MX Master, M720 Triathlon and a Corsiar Dark Core. They all show up and say they connect for a second, but I'm not able to move the cursor

**Comment by Talal916** [comment]
Yeah I have to use the matedock whenever I want to use wifi + mouse. Acceptable compromise imo, since the only time I'm using the mouse is if I'm sitting down at a table for an extended period of time. You can also use a miniature usb c to a adapter if you don't want something the size of a whole hub out everytime you want to use the mouse.

**Comment by byronpc** [comment]
i was able to connect the microsoft sculpt bluetooth mouse. maybe it's because of BTLE devices? (the mx master 2s is btle)

**Comment by byronpc** [comment]
BTW. another issue, I'm not sure if it is known, is after sleep, bluetooth will be disabled again. so we have to rerun vmware

**Comment by kilgil27** [comment]
Is does seem to be a BTLE issue, as I cannot get any BTLE devices to pair with the macOS side. All work fine on Windows

**Comment by byronpc** [comment]
@gnodipac886 btw, just an update. not related to btle issues but. I tried using the latest version of virtualsmc.kext, and i noticed that bluetooth seems to work even after restarting macos. 

Currently, when we reboot macos, the bluetooth will be disabled again and I have to rerun vmware to enable it. With the latest version, even after rebooting, bluetooth stays enabled.

From cold boot, it's still disabled. 

One caveat though, battery / processor info seems not working. Just thought you might know

**Comment by gnodipac886** [comment]
I did notice that bluetooth seems to persist after reboots too. Didn't know that it was due to virtualsmc.
What do you mean by "battery / processor info seems not working" I though you can see all that information in the system information page?

**Comment by byronpc** [comment]
i mean. i can't see battery % on the menu. cpu temp statistics from hwmonitor also gone. not same as yours?

**Comment by gnodipac886** [comment]
No... I think you forgot to add in the superIO and batterysmc kexts when you installed virtualSMC

**Comment by byronpc** [comment]
oh you are right. thanks! one less problem. thanks!

**Comment by Talal916** [comment]
Could you commit the latest virtualSMC.kext?
