### ISSUE TITLE
Install from windows crashes during "Reinstall macOS"

### ISSUE THREAD

**Issue by origamiman72** [gnodipac886/MatebookXPro-hackintosh#26]
I was able to use the install from windows on an external drive (from the matebook) and it boots perfectly, but when I tried to install it onto a partition of my internal ssd, it repeatedly crashes at around 2 minutes left after I press reinstall macOS. I've tried with the image from the install from Windows guide as well as a newer one I downloaded from my external drive hackintosh, and both have the same issue. My EFI is 600mb (although it is at the end of the drive). I can provide any logs if you need them, but I currently don't know how to get them. I've also tried with the partition as both APFS and HFS but I get the same problem.

**Comment by yamsboi** [comment]
What ssd are you using? Is it a Samsung PM981 or LiteOn?

**Comment by origamiman72** [comment]
Darn, I thought I remembered havin a LiteOn but I guess it's a samsung drive
