### ISSUE TITLE
Thunderbolt3 not working.

### ISSUE THREAD

**Issue by byronpc** [gnodipac886/MatebookXPro-hackintosh#27]
Tried plugging in an egpu. not detected. Tried with a real mac. detected

**Comment by gnodipac886** [comment]
Try pluging in the eGPU before booting the computer.

**Comment by byronpc** [comment]
negative. tried from cold boot and rebooting from windows. both show 

`  Thunderbolt:	No drivers are loaded.`

**Comment by gnodipac886** [comment]
There are some BIOS options on the thunderbolt on security, could you try messing with those?

**Comment by byronpc** [comment]
sure will update you

**Comment by byronpc** [comment]
unfortunately still not working. 

1. on bios, i set security to `no security`
2. added `SSDT-TB3.aml` to `/EFI/CLOVER/ACPI/patched` (btw i think this only addresses hotswapping right?) (renamed RP05 -> RP09)

mine doesn't even detect when being plugged while booting.

**Comment by gnodipac886** [comment]
Could you refer to these guides for an idea?
https://www.tonymacx86.com/threads/guide-dell-xps-9560-mojave-virtualsmc-i2c-trackpad-clover-uefi-hotpatch.263567/
https://github.com/the-darkvoid/XPS9360-macOS
https://github.com/daliansky/XiaoMi-Pro-Hackintosh
I think we might be missing a USB ssdt for the type C connection. Also we need that thunderbolt ssdt too.

**Comment by byronpc** [comment]
i've tried different ssdts. i'm not sure where to go on from here :)

**Comment by jacoweb** [comment]
TB3 working but not hotswap. I hope to find a working SSDT for this. Thank you for your work :)

**Comment by jacoweb** [comment]
i got hotplug working now. With this this SSDT:

https://drive.google.com/file/d/1-Msjoy_JkLW8uMljhCUUBG_JB7Cohh7K/view?usp=sharing

**Comment by gnodipac886** [comment]
Alright, the SSDT has been added to the repo.
