### ISSUE TITLE
"Copy here" in the window's installation guide

### ISSUE THREAD

**Issue by Guray00** [gnodipac886/MatebookXPro-hackintosh#30]
3. Launch TransMac (as an Administrator)
a. Select Tools from the top menu bar   OK
b. Go to Settings from the dropdown    OK
c. Select the Disk Drives tab from the new window OK
d. Select the Access non-removable drives read/write (use with caution) option, and then click OK to exit the window                            OK
e. Locate your USB in the left sidebar and navigate to OS X Base System/Install macOS Mojave.app/Contents                            OK
f. Right-click in the empty space in the main window and select Copy Here <--- How can i choose "copy here" if i haven't copied something? what am i missing? (i can't select it)
g. Navigate to Install macOS Mojave.app\Contents and select the SharedSupport folder <--- i don't have that folder in the USB, do you mean the folder i downloaded?
h. This should start copying the folder to your USB - this might take a while to complete. <--- how can it start coping if i haven't said it to him?

Sorry if I'm not understanding, if it his my bad i'm going to remove this issue, it is the only way to ask you

**Comment by gnodipac886** [comment]
@ayushyamitabh wrote the guide so he should be able to help you there.

**Comment by ayushyamitabh** [comment]
Hello!

So that process for installation is outdated now, for creating a Mac installation disk from windows use this 

https://github.com/corpnewt/gibMacOS

Run gibMacOS.bat first and then MakeInstall.bat

@gnodipac886 you can remove the guide from this repo or I can create a PR with this info 😊

**Comment by Guray00** [comment]
Maybe if u want i can create an Italian translation of the guide later (how can i send u?)... In addition let me know if u want to close this now.

Thanks for the reply and for your help!

**Comment by ayushyamitabh** [comment]
@gnodipac886  this can be closed, added proper instructions in PR #41
