### ISSUE TITLE
Reboot after running the auto installer never finishes

### ISSUE THREAD

**Issue by genaray** [gnodipac886/MatebookXPro-hackintosh#33]
Hey there ! 

I installed macos14.4 using unibeast and tried a combination of multibeast + your auto run script for the post install setup.

The script did run just fine and forced me to restart after on... Well... Clover theme was updated... I choosed "Boot mac os" as always and i started to show me the apple logo with a progressbar... The first half loaded fast... Then it took about half an hour to load the second half of the progressbar. 

Later on the bar was full... But nothing happened, i waited 10 more minutes without sucess... I decided to restart my laptop and try to boot again... The same happened as described above. 

![IMG_20190918_112626](https://user-images.githubusercontent.com/20269164/65137499-bfdcf300-da09-11e9-8bec-8fc42a963235.jpg)
![IMG_20190918_111322](https://user-images.githubusercontent.com/20269164/65137500-bfdcf300-da09-11e9-93a5-151b0184d0bb.jpg)

Should i just wait more ? Should it take such long ? Is there a way to reset the auto installer script ? Or the files it installed ? 

Hoping for a fast response :) and thanks for all your work !

**Comment by hefonthefjords** [comment]
I had the same problem while rebuilding my hackintosh after windows update wiped my clover EFI.
After this i couldn't get it to boot to mojave at all and ended up replacing the EFI partition with a backup image from my previously working build which i think was based on an older version of this repo.
Have yet to figure out what was preventing it from booting so for now im stuck with an older version of clover and all the previous bugs where sleep doesn't work properly etc. :(

**Comment by genaray** [comment]
I fixed this... just gave it another try and it worked wonderfull... :) Just make sure you install it in a clean way.
