### ISSUE TITLE
Incredible bad battery life ?

### ISSUE THREAD

**Issue by genaray** [gnodipac886/MatebookXPro-hackintosh#34]
I lately completed the guide for installing mac os on the matebook x pro.
Theres one issue... the battery life... its currently at 70% and tells me there 3-4 hours left of battery charge with auto adjusted screen brightness ( 50% ) and no other tasks open.

I already updated the CPUFriend & Data-Provider kexts... but they dont seem to improve the battery life... atleast i saw no effect.

Any ideas what else we can do ? Atleast 8-10 hours would be enough and close to the battery life at windows.

**Comment by gnodipac886** [comment]
I actually don't know, I had a peak of around 8-10 hours at one point, I did something and the battery life sucked, so I am trying to fix that in a future update, please wait patiently. :)
