### ISSUE TITLE
News on MateBook 13 port?

### ISSUE THREAD

**Issue by HenrikoMagnifico** [gnodipac886/MatebookXPro-hackintosh#36]
I would love to have this work on MateBook 13. Has anyone tried it? Does it already work?

Keep up the great work.
Thanks!

**Comment by ayushyamitabh** [comment]
If you have a Matebook 13 try it on there, from what I know most contributors to this project have a Matebook X Pro and so that's the device we tested it on.

Hit up Reddit r/Hackintosh with any issues you find along the way and people will definitely help you out

**Comment by gnodipac886** [comment]
There are several guides on github already, check this one out https://github.com/Edoardo001/Matebook-13-Hackintosh
or search "Matebook 13"
