### ISSUE TITLE
How to update Clover files?

### ISSUE THREAD

**Issue by Xpcker** [gnodipac886/MatebookXPro-hackintosh#38]
Hi Guys! thanks for all the information I manage to install everything perfectly :)

Reporting issues:
1. Random restarts seem that when I activate the Bluetooth it gets more often
2. When I close the lid, sometimes it goes to sleep, others just keep awake but I noticed that the clock its messed up when I open the lid in the morning,  if I go to sleep at 1 am usually it gets stuck at 4:50 am dunno if it points something out.
3. WiFi sometimes completely stop workings, gonna try to find out if a driver issue or not

Does anyone know how to update kexts in clover files?

thanks!

**Comment by gnodipac886** [comment]
I am going to update the repo soon, please wait and just replace the EFI file after or just run the script.
