### ISSUE TITLE
Problem when booting

### ISSUE THREAD

**Issue by MirzaCickusic** [gnodipac886/MatebookXPro-hackintosh#39]
I folow the guide. Since I dont have apple device I first went to install mac environment without it part of the guide. And I stucked on this screen https://imgur.com/QLmCtaJ (7th step). That what reads in guide is not representing what I see on the screen, I tried by guess and clicked on "Boot macOS install from OS X Base System" but I just get black screen and nothing else.

**Comment by gnodipac886** [comment]
@ayushyamitabh Should be able to help you.

**Comment by MirzaCickusic** [comment]
@ayushyamitabh hey man, would you be able to help me? :)

**Comment by ayushyamitabh** [comment]
@MirzaCickusic hey! The option you selected is correct but, I think you might have forgotten to copy over the clover files from this repo onto your USB. I would suggest deleting the contents of your Clover folder on your USB and then copying the contents that you downloaded from here. 

Hope this helps 😃
