### ISSUE TITLE
Occasional Crash in Mac OS Catalina

### ISSUE THREAD

**Issue by alex-spataru** [gnodipac886/MatebookXPro-hackintosh#40]
Hi!

I am currently running Mac OS Catalina with the kext's installed from this project and HoRNDIS 9.2 (to connect to the internet via USB tethering on my Android device). Everything works perfect most of the time, I really enjoy using this computer with Mac OS, I can say that it feels better to use it than Ubuntu or Windows on this machine :)

However, from time to time, the backlight turns off and the system is automatically rebooted, and I want to help to solve this issue. Unfortunately, I am still pretty noob with Hackintoshing (only done this on a Matebook and an HP Spectre x360), and I still don't know which information (or which terminal commands) should I use to get more info about these crashes and possibly help us arrive to a solution. I would really appreciate if somebody can tell me which commands to run in order to provide some relevant information.

Thanks for your work, I can say that configuring this computer was much more easier and straightforward than the HP Spectre, even on Catalina.

**Comment by Talal916** [comment]
How did you install Catalina?

**Comment by alex-spataru** [comment]
I installed Catalina using Niresh, I initially thought that it was an issue with the NVME, but if I boot the computer using the Niresh USB installer, the system does not crash at all.

**Comment by alex-spataru** [comment]
I've fixed the issue by removing all the Kext's placed by the Niresh install in `EFI/CLOVER/kexts/10.15/` and only leaving the Kexts installed by this project.
