### ISSUE TITLE
DRM Issue? Apple TV+ & Purchased Films don't work

### ISSUE THREAD

**Issue by AshleyMiller9696** [gnodipac886/MatebookXPro-hackintosh#43]
AppleTV+:
Flashes black and returns to the title

Purchased Films:
Error regarding a link to the Apple-ID

**Comment by gnodipac886** [comment]
Can you use your imessage or your app store in general?

**Comment by AshleyMiller9696** [comment]
Yes, no problem at all
Music via iTunes also works
