### ISSUE TITLE
10.15外置声音和commd键

### ISSUE THREAD

**Issue by a982027400** [gnodipac886/MatebookXPro-hackintosh#44]
我是在10.14.6版直接下载升级的，然后替换git上的clover，成功升级，目前蓝牙运行良好。
已知问题：
1. 外置喇叭无声音，插耳机或者蓝牙连音箱没问题
2. commd键无法使用（alt键现在是commd功能）
3. 睡眠有发热现象

是不是要重建缓存，需要怎么操作？

**Comment by AshleyMiller9696** [comment]
1. Sound works for me / with External Speaker you mean the ones from the Matebook?
2. Command Key also works for me / did you swap the special keys?

3. Sorry I can't understand that (Google Translate doesn't work great in chinese)

**Comment by a982027400** [comment]
1. External Speaker not work, I don't know why?
2. When I try to swap the special keys, now the Command key was ok.
3. Computer will be hot when sleeping.

**Comment by gnodipac886** [comment]
These issues should be fixed with the new update I'll push on 1/1.
