### ISSUE TITLE
Upgrading to Catalina

### ISSUE THREAD

**Issue by byronpc** [gnodipac886/MatebookXPro-hackintosh#45]
Guys,

For those who successfully upgraded to Catalina, how did you do it? I tried installing directly from the app store but when the machine reboots, it shoes the apple logo with the loader stuck at just 1%.

I also tried flashing the image to a flash drive and booting it, it gets to 100% eventually after a very long timem, but after that, it’s just there, stuck at 100%.

**Comment by AshleyMiller9696** [comment]
Updated through the app store but had an flash drive with Catalina & Clover to boot from as a "backup"
Did you update all the files from Clover?

**Comment by byronpc** [comment]
Yep. I tried verbose, it seems to get stuck at `VoodooPS2Mouse Version 1.9.2 starting...`

**Comment by gnodipac886** [comment]
Uh, install all my newest updated CLOVER files, and update through app store or settings.

**Comment by byronpc** [comment]
False alarm sorry guys
