### ISSUE TITLE
Boot problem

### ISSUE THREAD

**Issue by matetoosh** [gnodipac886/MatebookXPro-hackintosh#46]
I followed the steps to create my bootable usb with the script on the github. But Windows was getting started. So I did "Dual Booting Fix". I can start clover in verbose mode now but it stops on this line (""Lilu : user @ failed to change memory protection (0, 2)") and then the script starts again. The PC starts on Windows.
https://zupimages.net/up/19/47/bxdw.jpg

**Comment by gnodipac886** [comment]
@ayushyamitabh thank you :)

**Comment by ayushyamitabh** [comment]
@matetoosh this isn't something I've seen before but, I doubt this has to do with the Dual Booting Fix. Did you try booting into MacOS from your internal SSD after installing MacOS? After installing MacOS, you have to install Clover.

I would recommend installing MacOS first then Windows if that's a possibility for you
