### ISSUE TITLE
No WIFI on Catalina

### ISSUE THREAD

**Issue by kilgil27** [gnodipac886/MatebookXPro-hackintosh#47]
I have the edimax EW-7822ULC wifi dongle, and it was working fine in 10.14. Did a clean install of catalina, and I cannot get the wifi working. I installed the driver from [here ](https://www.edimax.com/edimax/download/download/data/edimax/global/download/for_home/wireless_adapters/wireless_adapters_ac1200_dual-band/ew-7822ulc) but no luck. The wifi utility doesn't seem to run and the computer doesn't recognize the wifi adapter. Am I missing something?

**Comment by gnodipac886** [comment]
https://github.com/chris1111/Wireless-USB-Adapter try this link, mine is working fine.

**Comment by kilgil27** [comment]
That worked. It's very very slow sometimes which might be an issue with the dongle itself but I'll keep messing around with it

**Comment by Talal916** [comment]
I'm using the Archer T2U Nano getting full speeds. Maybe you can try that?
