### ISSUE TITLE
High temperature

### ISSUE THREAD

**Issue by Guray00** [gnodipac886/MatebookXPro-hackintosh#50]
I have hackintosh 10.14 and i followed this guide. I have 50-56 Celsius in idle, is this normal? Am i missing some kexts? Thanks in advice

**Comment by willwaush** [comment]
I have 60 degrees Celsius in idle! It becomes very very hot. Is there a way to keep this cooled down like Windows? (around 35-40 degrees!)

**Comment by gnodipac886** [comment]
This will be solved on the next update.
