### ISSUE TITLE
Volume Mute button not working

### ISSUE THREAD

**Issue by willwaush** [gnodipac886/MatebookXPro-hackintosh#52]
Hello there.
I've installed Catalina 10.15.1 using your Clover folder but currently the volume mute button works just "graphically". I mean, when I click on it the mute popup shows up, but it doesn't really bring the volume to 0.
In System Pref->Volume the Mute option to tick is also greyed out and can't be engaged.

**Comment by gnodipac886** [comment]
Yeah, this is a known issue, I have yet had the time to make a custom ALC layout.

**Comment by gnodipac886** [comment]
Nevermind, I just fixed it, going to push the update 1/1.

**Comment by DaddySwift** [comment]
sooo... anyone figure out the fix?
