### ISSUE TITLE
Worrying random shutdown

### ISSUE THREAD

**Issue by willwaush** [gnodipac886/MatebookXPro-hackintosh#53]
Hello there. I'm using my Matebook Pro X with this hackintosh installation as a daily driver (Catalina 10.15.1). Today, after some hours of use, it randomly rebooted. I was just having some Chrome tasks and Word documents opened, nothing crazy. 
Also, the temperature of the laptop on macOs compared to Windows is very hot! Is there a way to solve this?

Anyway, there you go with the text report rescued after the random reboot.

`
panic(cpu 3 caller 0xffffff7f931f3718): "[IGPU] ERROR: SafeForceWake acknowledgement never received on GLOBAL domain, fFlags.systemInSleep: 0, fFlags.enabled: 1\n"@skl/IntelAccelerator.cpp:7585
Backtrace (CPU 3), Frame : Return Address
0xffffff8125fcb4e0 : 0xffffff8010139a3b 
0xffffff8125fcb530 : 0xffffff8010270fe5 
0xffffff8125fcb570 : 0xffffff8010262a5e 
0xffffff8125fcb5c0 : 0xffffff80100e0a40 
0xffffff8125fcb5e0 : 0xffffff8010139127 
0xffffff8125fcb6e0 : 0xffffff801013950b 
0xffffff8125fcb730 : 0xffffff80108d17f9 
0xffffff8125fcb7a0 : 0xffffff7f931f3718 
0xffffff8125fcb7d0 : 0xffffff7f9317dfd5 
0xffffff8125fcb820 : 0xffffff7f93178f83 
0xffffff8125fcb860 : 0xffffff7f9317dc47 
0xffffff8125fcb890 : 0xffffff7f9319a158 
0xffffff8125fcb8c0 : 0xffffff7f9319a0a1 
0xffffff8125fcb8e0 : 0xffffff7f9318a32a 
0xffffff8125fcb910 : 0xffffff7f930a4111 
0xffffff8125fcb970 : 0xffffff7f930c0660 
0xffffff8125fcb9e0 : 0xffffff7f930bcd63 
0xffffff8125fcba60 : 0xffffff8010867a51 
0xffffff8125fcbac0 : 0xffffff801086656c 
0xffffff8125fcbb10 : 0xffffff7f930be0e2 
0xffffff8125fcbb60 : 0xffffff801086f393 
0xffffff8125fcbca0 : 0xffffff8010220b92 
0xffffff8125fcbdb0 : 0xffffff801013f8b8 
0xffffff8125fcbe10 : 0xffffff8010116545 
0xffffff8125fcbe70 : 0xffffff801012cff5 
0xffffff8125fcbf00 : 0xffffff8010249085 
0xffffff8125fcbfa0 : 0xffffff80100e1226 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOAcceleratorFamily2(438.2.7)[72B8A0B5-E12C-3764-9187-0AC0E93416F9]@0xffffff7f93092000->0xffffff7f93155fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[180FC5AB-0E47-35BC-91DF-609EBE8ED4A5]@0xffffff7f91ec9000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[AA7C7A4F-9F5D-3533-9E78-177C3B6A72BF]@0xffffff7f90aec000
            dependency: com.apple.iokit.IOSurface(269.6)[39DC4195-B168-3895-ACD5-E731581855F8]@0xffffff7f93061000
            dependency: com.apple.iokit.IOGraphicsFamily(568)[247C211E-C250-351C-BCE2-4DB9D3003E10]@0xffffff7f92001000
            dependency: com.apple.iokit.IOReportFamily(47)[2CCA7DD3-C33F-3CA4-A213-BC83D3D997B0]@0xffffff7f91c00000
         com.apple.driver.AppleIntelKBLGraphics(14.0.2)[D21953DB-6324-350A-9A0C-A2EDC70A00AF]@0xffffff7f9316a000->0xffffff7f9325cfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[AA7C7A4F-9F5D-3533-9E78-177C3B6A72BF]@0xffffff7f90aec000
            dependency: com.apple.iokit.IOSurface(269.6)[39DC4195-B168-3895-ACD5-E731581855F8]@0xffffff7f93061000
            dependency: com.apple.iokit.IOGraphicsFamily(568)[247C211E-C250-351C-BCE2-4DB9D3003E10]@0xffffff7f92001000
            dependency: com.apple.iokit.IOAcceleratorFamily2(438.2.7)[72B8A0B5-E12C-3764-9187-0AC0E93416F9]@0xffffff7f93092000

BSD process name corresponding to current thread: Google Chrome He
Boot args: darkwake=0 dart=0 -cdfon -igfxmlr 

Mac OS version:
19B88

Kernel version:
Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
Kernel UUID: 7503CD47-851F-321E-8747-50DB4299165F
Kernel slide:     0x000000000fe00000
Kernel text base: 0xffffff8010000000
__HIB  text base: 0xffffff800ff00000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 19869317581584
last loaded kext at 257570617801: @filesystems.msdosfs	1.10 (addr 0xffffff7f92065000, size 69632)
last unloaded kext at 19773484301978: ru.joedm.SMCSuperIO	1.0.8 (addr 0xffffff7f9402d000, size 28672)
loaded kexts:
com.blankmac.VoodooI2CUPDDEngine	1
com.realtek.driver.RtWlanU	1830.32.b13
as.acidanthera.voodoo.driver.PS2Trackpad	2.0.4
as.acidanthera.voodoo.driver.PS2Keyboard	2.0.4
ru.joedm.SMCSuperIO	1.0.8
com.alexandred.VoodooI2CHID	1
com.alexandred.VoodooI2C	2.2
org.coolstar.VoodooGPIO	1.1
org.rehabman.driver.NullEthernet	1.0.6
as.acidanthera.voodoo.driver.PS2!C	2.0.4
as.vit9696.SMCProcessor	1.0.8
as.vit9696.!AALC	1.4.2
org.tw.CodecCommander	2.7.1
org.vanilla.driver.CPUFriend	1.1.9
as.lvs1974.HibernationFixup	1.2.9
xyz.racermaster.NoTouchID	1.0.2
com.rehabman.driver.USBInjectAll	0.7.1
ru.usrsse2.SMCBatteryManager	1
ru.usrsse2.SMCLightSensor	1
as.vit9696.VirtualSMC	1.0.8
com.alexandred.VoodooI2CServices	1
as.vit9696.WhateverGreen	1.3.3
as.vit9696.Lilu	1.3.8
>AudioAUUC	1.70
@fileutil	20.036.15
@filesystems.autofs	3.0
@filesystems.ntfs	3.14.3
>AGPM	111.2.5
>X86PlatformShim	1.0.0
>!APlatformEnabler	2.7.0d0
>!AUpstreamUserClient	3.6.8
>!AHDA	283.14
>!AGraphicsDevicePolicy	4.5.9
@AGDCPluginDisplayMetrics	4.5.9
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.1f1
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
@private.KextAudit	1.0
>!A!ISlowAdaptiveClocking	4.0.0
>eficheck	1
>!A!IKBLGraphics	14.0.2
>!A!IPCHPMC	2.0.1
>!ASMCLMU	212
>!ABacklight	180.1
>!AMCCSControl	1.13
>!A!IKBLGraphicsFramebuffer	14.0.2
>usb.realtek8153patcher	5.0.0
>!ATopCaseHIDEventDriver	3410.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.0.9
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.41.1
>!ASmartBatteryManager	161.0.0
>!AHPET	1.8
>!AACPIEC	6.1
>!AACPIButtons	6.1
>!ARTC	2.0
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
@kext.triggers	1.0
>DspFuncLib	283.14
@kext.OSvKernDSPLib	529
>!AGraphicsControl	4.5.9
|IOAVB!F	800.17
>!ASSE	1.0
@!AGPUWrangler	4.5.9
|IOSlowAdaptiveClocking!F	1.0.0
>!AHDA!C	283.14
|IOHDA!F	283.14
|IO!BHost!CUSBTransport	7.0.1f1
|IO!BHost!CTransport	7.0.1f1
>!ABacklightExpert	1.1.0
|IONDRVSupport	568
>!ASMBus!C	1.0.18d1
@!AGraphicsDeviceControl	4.5.9
|IOAccelerator!F2	438.2.7
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
@plugin.IOgPTPPlugin	810.1
|IOEthernetAVB!C	1.1.0
|IOSkywalk!F	1
>!AActuatorDriver	3410.2
>!AHS!BDriver	3410.1
>IO!BHIDDriver	7.0.1f1
|IO!B!F	7.0.1f1
|IO!BPacketLogger	7.0.1f1
>!AMultitouchDriver	3410.2
>!AInputDeviceSupport	3410.1
>usb.!UHub	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IOSerial!F	11
|IOSurface	269.6
@filesystems.hfs.encodings.kext	1
|IONVMe!F	2.1.0
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOGraphics!F	568
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSMBus!F	1.1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.41.1
|IOSCSIBlockCommandsDevice	422.0.2
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.40.7
|IOSCSIArchitectureModel!F	422.0.2
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	810.1
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1
`

**Comment by gnodipac886** [comment]
Should have been fixed with Jan 2020 update
