### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by masenov** [gnodipac886/MatebookXPro-hackintosh#54]
Does anyone has any trouble with the audio? The speakers show up in settings, and I can "change" the volume with the keys, but I am getting no sound.

I am on Catalina 10.15.2

**Comment by AshleyMiller9696** [comment]
No trouble for me
/Catalina 10.15.1

**Comment by willwaush** [comment]
On mine (Catalina 10.15.2) it's working fine. 
The only issue I have is with the Volume mute button which even if pressed, doesn't actually mute the volume. Try checking your audio kexts. I'm using the ones coming from this repo's folder and haven't updated them.

**Comment by masenov** [comment]
Thanks, I will do a clean install and check again.

**Comment by masenov** [comment]
I did a clean install, but unfortunately it is still not working :/
Do you do anything part from what is mentioned in the Readme file of the repository?
I tried injecting all the different IDs (layout 5, 11, 13, 14, 21, 22, 28, 56, 57, 66, 97) via Clover->Devices->Inject according to the specification, but still not success :/
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs

**Comment by gnodipac886** [comment]
Use ID 97, its tailored for this laptop

**Comment by masenov** [comment]
Interestingly enough for me ID 97 did not work for me, but 14 did.

I had to change it from Clover->Devices->Properties->layout-id, not what I mentioned in the previous comment.

Thanks everyone for the help!
