### ISSUE TITLE
Audio Playing from 2/4 Speakers

### ISSUE THREAD

**Issue by Grippy98** [gnodipac886/MatebookXPro-hackintosh#56]
Hey, have you guys tried patching this using a custom AppleALC already or is this something that's been tried and given up on?

I'm willing to take a look at it if that's the case (have some experience with Linux ALSA) 

If you have the changes you did to ALC already posted somewhere let me know. Thanks!

**Comment by gnodipac886** [comment]
Yea, actually. 
https://github.com/acidanthera/AppleALC/blob/master/Resources/ALC256/layout97.xml
ALC 256 is ours and there has been an effort. LayoutID 97 is ours. There are some issues and I have yet to have the time to fix it. 
https://github.com/headkaze/PinConfigurator
heres a tool that could help you. 

I would actually love to work if you would like.

**Comment by gnodipac886** [comment]
solved actually with new update

**Comment by hjmmc** [comment]
You can use [layout-id 17](https://github.com/acidanthera/AppleALC/pull/529) (has LineIn) or [layout-id 76](https://github.com/acidanthera/AppleALC/pull/562) (no LineIn) to enable 4/4 speakers
