### ISSUE TITLE
i5 MateBookXPro "... Testing Hardware ..."

### ISSUE THREAD

**Issue by Doty1154** [gnodipac886/MatebookXPro-hackintosh#57]
Howdy,
 I'm trying to install from USB using the windows usb creation method and my i5 MatebookXPro doesn't get past a black screen saying "... Testing Hardware..." Perhaps its looking for the NVIDIA GPU? I've tried looking through the config and i've not seen any references to the DGPU explicitly.
Heres my debug.log from clover.
I've tried letting it boot for 30Minutes and it just is stuck. 

0:100  0:100  MemLog inited, TSC freq: 1795978840
0:100  0:000  CPU was calibrated with RTC
0:100  0:000  
0:100  0:000  Now is 31.12.2019,  22:43:22 (GMT)
0:100  0:000  Starting Clover revision: 5102 (HEAD, commit 12d559ae) on HUAWEI EFI
0:100  0:000  Build with: [Args: --x64-mcp --no-usb -D NO_GRUB_DRIVERS_EMBEDDED -t XCODE8 | -D DISABLE_USB_SUPPORT -D NO_GRUB_DRIVERS_EMBEDDED --conf=/Users/vagrant/.clobber/src/Clover/Conf -D USE_BIOS_BLOCKIO -D USE_LOW_EBDA -a X64 -b RELEASE -t XCODE8 -n 3 | OS: 10.14.6]
0:100  0:000  SelfDevicePath=PciRoot(0x0)\Pci(0x14,0x0)\USB(0xD,0x0)\HD(1,GPT,B884B66A-0725-43C9-8C06-A91179E74179,0x800,0x64000) @5FC6F9D8
0:100  0:000  SelfDirPath = \EFI\BOOT
0:100  0:000  SimpleTextEx Status=Success
0:100  0:000  === [ Get Smbios ] ========================================
0:105  0:004  Type 16 Index = 0
0:105  0:000  Total Memory Slots Count = 2
0:105  0:000  Type 17 Index = 0
0:105  0:000  SmbiosTable.Type17->Speed = 2133MHz
0:105  0:000  SmbiosTable.Type17->Size = 4096MB
0:105  0:000  SmbiosTable.Type17->Bank/Device = BANK 0 ChannelA-DIMM0
0:105  0:000  SmbiosTable.Type17->Vendor = Micron
0:105  0:000  SmbiosTable.Type17->SerialNumber = 00000000
0:105  0:000  SmbiosTable.Type17->PartNumber = MT52L512M32D2PF-09
0:105  0:000  Type 17 Index = 1
0:105  0:000  SmbiosTable.Type17->Speed = 2133MHz
0:105  0:000  SmbiosTable.Type17->Size = 4096MB
0:105  0:000  SmbiosTable.Type17->Bank/Device = BANK 2 ChannelB-DIMM0
0:105  0:000  SmbiosTable.Type17->Vendor = Micron
0:105  0:000  SmbiosTable.Type17->SerialNumber = 00000000
0:105  0:000  SmbiosTable.Type17->PartNumber = MT52L512M32D2PF-09
0:105  0:000  Boot status=0
0:105  0:000  Running on: 'MACH-WX9' with board 'MACH-WX9'
0:105  0:000  === [ GetCPUProperties ] ==================================
0:105  0:000  CPU Vendor = 756E6547 Model=806EA
0:105  0:000   The CPU supported SSE4.1
0:105  0:000  BrandString = Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
0:105  0:000   The CPU supported turbo
0:105  0:000  MSR 0x35               40008
0:105  0:000   TSC/CCC Information Leaf:
0:105  0:000    numerator     : 150
0:105  0:000    denominator   : 2
0:105  0:000   Calibrated ARTFrequency: 23946384
0:105  0:000   Rounded ARTFrequency: 23900000
0:105  0:000  MSR 0xE2 before patch 1E008008
0:105  0:000  MSR 0xE2 is locked, PM patches will be turned on
0:105  0:000  MSR 0xCE              0004043D_F1011200
0:105  0:000  corrected FLEX_RATIO = 0
0:105  0:000  MSR 0x1B0             00000000
0:105  0:000  FSBFrequency = 150 MHz, DMI FSBFrequency = 100 MHz, Corrected FSBFrequency = 100 MHz
0:105  0:000  MaxDiv/MinDiv: 18.0/4
0:105  0:000  Turbo: 34/34/34/34
0:105  0:000  Features: 0xBFEBFBFF
0:105  0:000  Threads: 8
0:105  0:000  Cores: 4
0:105  0:000  FSB: 100 MHz
0:105  0:000  CPU: 2700 MHz
0:105  0:000  TSC: 2700 MHz
0:105  0:000  PIS: 100 MHz
0:105  0:000  ExternalClock: 25 MHz
0:105  0:000  === [ GetDevices ] ========================================
0:105  0:000  GOP found at: PciRoot(0x0)/Pci(0x2,0x0)/AcpiAdr(0x80011400)
0:105  0:000  PCI (00|00:00.00) : 8086 5914 class=060000
0:105  0:000  PCI (00|00:02.00) : 8086 5917 class=030000
0:105  0:000   - GOP: Provided by device
0:105  0:000   - GFX: Model=Intel UHD Graphics 620 (Intel)
0:105  0:000  PCI (00|00:04.00) : 8086 1903 class=118000
0:105  0:000  PCI (00|00:14.00) : 8086 9D2F class=0C0330
0:105  0:000  PCI (00|00:14.02) : 8086 9D31 class=118000
0:105  0:000  PCI (00|00:15.00) : 8086 9D60 class=118000
0:105  0:000  PCI (00|00:15.01) : 8086 9D61 class=118000
0:105  0:000  PCI (00|00:16.00) : 8086 9D3A class=078000
0:105  0:000  PCI (00|00:1C.00) : 8086 9D14 class=060400
0:105  0:000  PCI (00|01:00.00) : 14A4 2300 class=010802
0:105  0:000  PCI (00|00:1D.00) : 8086 9D18 class=060400
0:105  0:000  PCI (00|00:1D.02) : 8086 9D1A class=060400
0:105  0:000  PCI (00|3B:00.00) : 8086 24FD class=028000
0:105  0:000   - WIFI: Vendor=Intel
0:106  0:000  PCI (00|00:1E.00) : 8086 9D27 class=118000
0:106  0:000  PCI (00|00:1E.03) : 8086 9D2A class=118000
0:106  0:000  PCI (00|00:1F.00) : 8086 9D4E class=060100
0:106  0:000  PCI (00|00:1F.02) : 8086 9D21 class=058000
0:106  0:000  PCI (00|00:1F.03) : 8086 9D71 class=040300
0:106  0:000  PCI (00|00:1F.04) : 8086 9D23 class=0C0500
0:106  0:000  === [ GetDefaultSettings ] ================================
0:106  0:000  Clover load options size = 0 bytes
0:110  0:004  CheckOEMPathExists tried EFI\CLOVER\OEM\MACH-WX9\UEFI. Dir not exists
0:110  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\MACH-WX9. Dir not exists
0:110  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\MACH-WX9-2700. Dir not exists
0:110  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\MACH-WX9. Dir not exists
0:110  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\MACH-WX9-2700. Dir not exists
0:110  0:000  set OEMPath by default: EFI\CLOVER
0:114  0:004  EFI\CLOVER\config.plist loaded: Success
0:120  0:005  === [ GetListOfThemes ] ===================================
0:124  0:003  - [00]: bootcamp
0:129  0:004  - [01]: christmas
0:133  0:003  - [02]: embedded
0:134  0:001  - [02]: Huawei
0:136  0:001  - [03]: newyear
0:142  0:005  - [04]: random
0:144  0:002  === [ Found config plists ] ===============================
0:144  0:000  - config.plist
0:144  0:000  - config-install.plist
0:144  0:000  === [ GetEarlyUserSettings ] ==============================
0:144  0:000  timeout set to 4
0:144  0:000  Custom boot CUSTOM_BOOT_DISABLED (0x0)
0:305  0:160  ForceKextsToLoad: 2 requested
0:315  0:010   - [0]: System\Library\Extensions\IOGraphicsFamily.kext
0:326  0:010   - [1]: System\Library\Extensions\IONetworkingFamily.kext
0:337  0:010  KextsToPatch: 3 requested
0:348  0:010   - [00]: IONVMeFamily (IONVMeFamily: Ignore FLBAS bit:4 being set - for Plextor/LiteOn/Hynix) :: BinPatch :: data len: 7
0:401  0:052   - [01]: com.apple.driver.AppleIntelLpssI2C (Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar) :: PlistPatch :: data len: 5
0:443  0:042   - [02]: com.apple.driver.AppleIntelLpssI2CController (Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar) :: PlistPatch :: data len: 5
0:551  0:108  KernelToPatch: 3 requested
0:563  0:011   - [00]: MSR 0xE2 _xcpm_idle instant reboot(c) Pike R. Alpha :: data len: 8
0:591  0:028   - [01]: Disable panic kext logging on 10.13 release kernel (credit vit9696) :: MatchOS: 10.13.x :: data len: 6
0:639  0:047   - [02]: Disable panic kext logging on 10.14 release kernel (credit vit9696) :: MatchOS: 10.14.x :: data len: 6
0:678  0:039  Default theme: Huawei
0:688  0:009  Hiding entries with string Preboot
0:698  0:009  === [ LoadDrivers ] =======================================
1:131  0:433  Loading ApfsDriverLoader.efi  status=Success
1:205  0:074   - driver needs connecting
1:214  0:009  Loading AptioInputFix.efi  status=Success
1:349  0:134  Loading AptioMemoryFix.efi  status=Success
1:497  0:148  Loading AudioDxe.efi  status=Success
1:541  0:044   - driver needs connecting
1:551  0:009  Loading DataHubDxe.efi  status=Success
1:583  0:031  Loading Fat.efi  status=Success
1:615  0:031   - driver needs connecting
1:624  0:009  Loading FSInject.efi  status=Success
1:657  0:032  Loading FwRuntimeServices.efi  status=Success
1:698  0:040  Loading HFSPlus.efi  status=Success
1:729  0:031   - driver needs connecting
1:739  0:009  Loading OcQuirks.efi  status=Success
1:779  0:039  Loading SMCHelper.efi  status=Success
1:810  0:031  Loading VBoxHfs.efi  status=Success
1:844  0:033   - driver needs connecting
1:863  0:018  5 drivers needs connecting ...
1:873  0:009  PlatformDriverOverrideProtocol->GetDriver overriden
1:882  0:009  HFS+ driver loaded
1:892  0:009  APFS driver loaded
1:902  0:009  Searching for invalid DiskIo BY_DRIVER connects: not found, all ok
5:774  3:871  === [ InitScreen ] ========================================
6:372  0:597  Console modes reported: 9, available modes:
6:382  0:009   - [01]: 80x25
6:392  0:010   - [02]: 80x50
6:402  0:009   - [03]: 80x25
6:420  0:018   - [04]: 375x105 (current mode)
6:430  0:009   - [05]: 100x31
6:463  0:032   - [06]: 128x40
6:474  0:010   - [07]: 160x53
6:485  0:010   - [08]: 200x63
6:496  0:010   - [09]: 240x75
6:507  0:010  SetMaxResolution: found best mode 0: 3000x2000
6:529  0:022   - already set
6:540  0:011  SetScreenResolution: 3000x2000 - already set
6:562  0:022  reinit: self device path=PciRoot(0x0)\Pci(0x14,0x0)\USB(0xD,0x0)\HD(1,GPT,B884B66A-0725-43C9-8C06-A91179E74179,0x800,0x64000)
6:573  0:011  Using embedded font: Success
6:585  0:011  === [ GetMacAddress ] =====================================
0:100  0:100  MemLog inited, TSC freq: 1796204090
0:100  0:000  CPU was calibrated with RTC
0:100  0:000  
0:100  0:000  Now is 31.12.2019,  22:50:28 (GMT)
0:100  0:000  Starting Clover revision: 5102 (HEAD, commit 12d559ae) on HUAWEI EFI
0:100  0:000  Build with: [Args: --x64-mcp --no-usb -D NO_GRUB_DRIVERS_EMBEDDED -t XCODE8 | -D DISABLE_USB_SUPPORT -D NO_GRUB_DRIVERS_EMBEDDED --conf=/Users/vagrant/.clobber/src/Clover/Conf -D USE_BIOS_BLOCKIO -D USE_LOW_EBDA -a X64 -b RELEASE -t XCODE8 -n 3 | OS: 10.14.6]
0:100  0:000  SelfDevicePath=PciRoot(0x0)\Pci(0x14,0x0)\USB(0xD,0x0)\HD(1,GPT,B884B66A-0725-43C9-8C06-A91179E74179,0x800,0x64000) @5FC79358
0:100  0:000  SelfDirPath = \EFI\BOOT
0:100  0:000  SimpleTextEx Status=Success
0:100  0:000  === [ Get Smbios ] ========================================
0:105  0:004  Type 16 Index = 0
0:105  0:000  Total Memory Slots Count = 2
0:105  0:000  Type 17 Index = 0
0:105  0:000  SmbiosTable.Type17->Speed = 2133MHz
0:105  0:000  SmbiosTable.Type17->Size = 4096MB
0:105  0:000  SmbiosTable.Type17->Bank/Device = BANK 0 ChannelA-DIMM0
0:105  0:000  SmbiosTable.Type17->Vendor = Micron
0:105  0:000  SmbiosTable.Type17->SerialNumber = 00000000
0:105  0:000  SmbiosTable.Type17->PartNumber = MT52L512M32D2PF-09
0:105  0:000  Type 17 Index = 1
0:105  0:000  SmbiosTable.Type17->Speed = 2133MHz
0:105  0:000  SmbiosTable.Type17->Size = 4096MB
0:105  0:000  SmbiosTable.Type17->Bank/Device = BANK 2 ChannelB-DIMM0
0:105  0:000  SmbiosTable.Type17->Vendor = Micron
0:105  0:000  SmbiosTable.Type17->SerialNumber = 00000000
0:105  0:000  SmbiosTable.Type17->PartNumber = MT52L512M32D2PF-09
0:105  0:000  Boot status=0
0:105  0:000  Running on: 'MACH-WX9' with board 'MACH-WX9'
0:105  0:000  === [ GetCPUProperties ] ==================================
0:105  0:000  CPU Vendor = 756E6547 Model=806EA
0:105  0:000   The CPU supported SSE4.1
0:105  0:000  BrandString = Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
0:105  0:000   The CPU supported turbo
0:105  0:000  MSR 0x35               40008
0:105  0:000   TSC/CCC Information Leaf:
0:105  0:000    numerator     : 150
0:105  0:000    denominator   : 2
0:105  0:000   Calibrated ARTFrequency: 23949387
0:105  0:000   Rounded ARTFrequency: 23900000
0:105  0:000  MSR 0xE2 before patch 1E008008
0:105  0:000  MSR 0xE2 is locked, PM patches will be turned on
0:105  0:000  MSR 0xCE              0004043D_F1011200
0:105  0:000  corrected FLEX_RATIO = 0
0:105  0:000  MSR 0x1B0             00000000
0:105  0:000  FSBFrequency = 156 MHz, DMI FSBFrequency = 100 MHz, Corrected FSBFrequency = 100 MHz
0:105  0:000  MaxDiv/MinDiv: 18.0/4
0:105  0:000  Turbo: 34/34/34/34
0:105  0:000  Features: 0xBFEBFBFF
0:105  0:000  Threads: 8
0:105  0:000  Cores: 4
0:105  0:000  FSB: 100 MHz
0:105  0:000  CPU: 2800 MHz
0:105  0:000  TSC: 2800 MHz
0:105  0:000  PIS: 100 MHz
0:105  0:000  ExternalClock: 25 MHz
0:105  0:000  === [ GetDevices ] ========================================
0:105  0:000  GOP found at: PciRoot(0x0)/Pci(0x2,0x0)/AcpiAdr(0x80011400)
0:105  0:000  PCI (00|00:00.00) : 8086 5914 class=060000
0:105  0:000  PCI (00|00:02.00) : 8086 5917 class=030000
0:105  0:000   - GOP: Provided by device
0:105  0:000   - GFX: Model=Intel UHD Graphics 620 (Intel)
0:105  0:000  PCI (00|00:04.00) : 8086 1903 class=118000
0:105  0:000  PCI (00|00:14.00) : 8086 9D2F class=0C0330
0:105  0:000  PCI (00|00:14.02) : 8086 9D31 class=118000
0:105  0:000  PCI (00|00:15.00) : 8086 9D60 class=118000
0:105  0:000  PCI (00|00:15.01) : 8086 9D61 class=118000
0:105  0:000  PCI (00|00:16.00) : 8086 9D3A class=078000
0:105  0:000  PCI (00|00:1C.00) : 8086 9D14 class=060400
0:105  0:000  PCI (00|01:00.00) : 14A4 2300 class=010802
0:105  0:000  PCI (00|00:1D.00) : 8086 9D18 class=060400
0:105  0:000  PCI (00|00:1D.02) : 8086 9D1A class=060400
0:105  0:000  PCI (00|3B:00.00) : 8086 24FD class=028000
0:105  0:000   - WIFI: Vendor=Intel
0:105  0:000  PCI (00|00:1E.00) : 8086 9D27 class=118000
0:105  0:000  PCI (00|00:1E.03) : 8086 9D2A class=118000
0:106  0:000  PCI (00|00:1F.00) : 8086 9D4E class=060100
0:106  0:000  PCI (00|00:1F.02) : 8086 9D21 class=058000
0:106  0:000  PCI (00|00:1F.03) : 8086 9D71 class=040300
0:106  0:000  PCI (00|00:1F.04) : 8086 9D23 class=0C0500
0:106  0:000  === [ GetDefaultSettings ] ================================
0:106  0:000  Clover load options size = 0 bytes
0:108  0:002  CheckOEMPathExists tried EFI\CLOVER\OEM\MACH-WX9\UEFI. Dir not exists
0:108  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\MACH-WX9. Dir not exists
0:108  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\MACH-WX9-2800. Dir not exists
0:108  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\MACH-WX9. Dir not exists
0:108  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\MACH-WX9-2800. Dir not exists
0:108  0:000  set OEMPath by default: EFI\CLOVER
0:112  0:004  EFI\CLOVER\config.plist loaded: Success
0:119  0:006  === [ GetListOfThemes ] ===================================
0:123  0:004  - [00]: bootcamp
0:128  0:005  - [01]: christmas
0:132  0:003  - [02]: embedded
0:133  0:001  - [02]: Huawei
0:135  0:001  - [03]: newyear
0:140  0:005  - [04]: random
0:142  0:001  === [ Found config plists ] ===============================
0:142  0:000  - config.plist
0:142  0:000  - config-install.plist
0:142  0:000  === [ GetEarlyUserSettings ] ==============================
0:142  0:000  timeout set to 4
0:142  0:000  Custom boot CUSTOM_BOOT_DISABLED (0x0)
0:198  0:055  ForceKextsToLoad: 2 requested
0:209  0:010   - [0]: System\Library\Extensions\IOGraphicsFamily.kext
0:248  0:038   - [1]: System\Library\Extensions\IONetworkingFamily.kext
0:258  0:010  KextsToPatch: 3 requested
0:269  0:010   - [00]: IONVMeFamily (IONVMeFamily: Ignore FLBAS bit:4 being set - for Plextor/LiteOn/Hynix) :: BinPatch :: data len: 7
0:321  0:052   - [01]: com.apple.driver.AppleIntelLpssI2C (Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar) :: PlistPatch :: data len: 5
0:365  0:043   - [02]: com.apple.driver.AppleIntelLpssI2CController (Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar) :: PlistPatch :: data len: 5
0:408  0:042  KernelToPatch: 3 requested
0:419  0:011   - [00]: MSR 0xE2 _xcpm_idle instant reboot(c) Pike R. Alpha :: data len: 8
0:458  0:039   - [01]: Disable panic kext logging on 10.13 release kernel (credit vit9696) :: MatchOS: 10.13.x :: data len: 6
0:546  0:087   - [02]: Disable panic kext logging on 10.14 release kernel (credit vit9696) :: MatchOS: 10.14.x :: data len: 6
0:589  0:043  Default theme: Huawei
0:600  0:010  Hiding entries with string Preboot
0:611  0:010  === [ LoadDrivers ] =======================================
1:088  0:477  Loading ApfsDriverLoader.efi  status=Success
1:127  0:039   - driver needs connecting
1:138  0:010  Loading AptioInputFix.efi  status=Success
1:322  0:183  Loading AptioMemoryFix.efi  status=Success
1:654  0:331  Loading AudioDxe.efi  status=Success
1:810  0:156   - driver needs connecting
1:821  0:010  Loading DataHubDxe.efi  status=Success
1:856  0:034  Loading Fat.efi  status=Success
1:891  0:034   - driver needs connecting
1:901  0:010  Loading FSInject.efi  status=Success
1:938  0:036  Loading FwRuntimeServices.efi  status=Success
1:981  0:043  Loading HFSPlus.efi  status=Success
2:015  0:034   - driver needs connecting
2:026  0:010  Loading OcQuirks.efi  status=Success
2:064  0:037  Loading SMCHelper.efi  status=Success
2:099  0:034  Loading VBoxHfs.efi  status=Success
2:136  0:037   - driver needs connecting
2:181  0:045  5 drivers needs connecting ...
2:191  0:009  PlatformDriverOverrideProtocol->GetDriver overriden
2:201  0:009  HFS+ driver loaded
2:211  0:009  APFS driver loaded
2:220  0:009  Searching for invalid DiskIo BY_DRIVER connects: not found, all ok
6:025  3:805  === [ InitScreen ] ========================================
6:509  0:483  Console modes reported: 9, available modes:
6:519  0:009   - [01]: 80x25
6:529  0:009   - [02]: 80x50
6:539  0:009   - [03]: 80x25
6:549  0:009   - [04]: 375x105 (current mode)
6:559  0:009   - [05]: 100x31
6:569  0:009   - [06]: 128x40
6:579  0:009   - [07]: 160x53
6:588  0:009   - [08]: 200x63
6:598  0:009   - [09]: 240x75
6:608  0:009  SetMaxResolution: found best mode 0: 3000x2000
6:636  0:027   - already set
6:646  0:009  SetScreenResolution: 3000x2000 - already set
6:665  0:019  reinit: self device path=PciRoot(0x0)\Pci(0x14,0x0)\USB(0xD,0x0)\HD(1,GPT,B884B66A-0725-43C9-8C06-A91179E74179,0x800,0x64000)
6:675  0:010  Using embedded font: Success
6:686  0:010  === [ GetMacAddress ] =====================================

**Comment by raviley** [comment]
I had the exact same problem and figured it out. The CLOVER "drivers" folder has a different folder tree than the usb when using the windows usb creation method. Assuming you tried using the script and have your EFI mounted:

Copy all the files from gnodipac886's folder:
CLOVER/drivers64UEFI
to your EFI
/Volumes/CLOVER/EFI/CLOVER/drivers/UEFI

Do the same for all files in gnodipac886's folder:
CLOVER/drivers64
to
/Volumes/CLOVER/EFI/CLOVER/drivers/BIOS

From there I was able to complete the install.

**Comment by Doty1154** [comment]
Huh.. that appears to be it. 
I'm also noticed this issue https://github.com/gnodipac886/MatebookXPro-hackintosh/issues/55
I had a second mac on hand so i was able to create a boot/install drive with that.
I think Macs add some sort of metadata to the partition to verify authenticity, and installing via windows removes the authenticity.
 But with the image from the mac and your script i was able to install Mac Catalina on my i5 matebook, its pretty amazing so far. Great work!
I have been noticing when i tell it to go to sleep there are often kernel panics, but its so quick to shutdown/power on i don't think this is a massive issue. Heres the report text/crashlog
[kernelpanic.txt](https://github.com/gnodipac886/MatebookXPro-hackintosh/files/4021476/kernelpanic.txt)

**Comment by gnodipac886** [comment]
This is commonly seen due to the USB not working right, I think I need to fix this next time I decide to operate. For now, I think you can boot with the USB not plugged in, and people have reported that that fixes the issue.
