### ISSUE TITLE
Volume button,4 speakers, sleep

### ISSUE THREAD

**Issue by willwaush** [gnodipac886/MatebookXPro-hackintosh#58]
I have updated the Clover folder with the new kexts, but I still have the volume button issue and even trying the Midi solution only two speakers are working (and not 4).
Sleep has still got issues, the laptop suddently wakes up while the solution of deleting an USB kext posted here solved the issue completely with the previous version of the kexts.

**Comment by AshleyMiller9696** [comment]
Volume Buttons + 4 Speakers will not work

No issues for me with sleeping

**Comment by willwaush** [comment]
Okay, I can confirm, after a fresh install sleep works again. But no volume button and no 4 speakers.

**Comment by gnodipac886** [comment]
I think the 4 speakers should work, but due to macOS being macOS, you can't control the volume of these mutioutput devices.

**Comment by willwaush** [comment]
Okay, but still volume mute button is not working at all even if you flagged it as solved in the update notes

**Comment by AshleyMiller9696** [comment]
All Buttons work for me
