### ISSUE TITLE
Sidecar Error 6709

### ISSUE THREAD

**Issue by Suhas7** [gnodipac886/MatebookXPro-hackintosh#61]
It seems like Sidecar isn't working- I connected an iPad Pro 2018 and made both devices trust each other, and made sure handoff/wifi/bluetooth was all setup. When I try to activate sidecar over the wired connection, it says it encountered an error code 6709 miscellaneous error.

**Comment by Suhas7** [comment]
Ope resolved this too, I ran the following commands:
sudo defaults write com.apple.sidecar.display allowAllDevices -bool YES
sudo defaults write com.apple.sidecar.display hasShownPref -bool YES

**Comment by kvn1351** [comment]
@Suhas7 what wifi+bluetooth combo are you using?

**Comment by Suhas7** [comment]
I was using the Edimax 2.4ghz adapter. No bluetooth. I had to use sidecar wired, I didn't get wireless to work.

**Comment by kvn1351** [comment]
Thanks for your reply!
