### ISSUE TITLE
Bluetooth not recognized

### ISSUE THREAD

**Issue by Venipa** [gnodipac886/MatebookXPro-hackintosh#67]
<img width="219" alt="Screenshot 2020-01-11 at 23 22 32" src="https://user-images.githubusercontent.com/17952364/72211306-578ab380-34c9-11ea-9afd-24a8b8cdee39.png">

**Comment by Venipa** [comment]
using 1/1 Update

**Comment by gnodipac886** [comment]
That happens a lot due to the beta phase bluetooth kext.

**Comment by Venipa** [comment]
I'll try that

**Comment by Venipa** [comment]
cold boot enabled it this time
