### ISSUE TITLE
Power Management

### ISSUE THREAD

**Issue by Venipa** [gnodipac886/MatebookXPro-hackintosh#68]
Power is still being drained fast

**Comment by kmonty** [comment]
This issue isn't really helpful and should probably be closed, but it sounds like the cause of the issue was discovered and being addressed (USB ports sucking up a ton of energy after sleep): https://www.reddit.com/r/MatebookXPro/comments/eiutbq/hackintosh_update_of_the_decade/fcx5bf7/

**Comment by Venipa** [comment]
@kmonty not really since the battery is drained fast while no ports are occupied while my testing.

**Comment by gnodipac886** [comment]
Most likely bluetooth, should be addressed already.
