### ISSUE TITLE
Update from 10.14.0 to 10.14.4 results in unbootable OS

### ISSUE THREAD

**Issue by joshzhang5** [gnodipac886/MatebookXPro-hackintosh#7]
I copied the last CLOVER folder into my EFI however now the OS won't boot. Did I miss any steps while updating?

**Comment by gnodipac886** [comment]
You would need to choose which config to use.

**Comment by joshzhang5** [comment]
Which config should I use? Tried all of the ones in the current commit

**Comment by gnodipac886** [comment]
You might have to do a clean install and just transfer files over, the old way of hackintoshing could haave resulted in a really messy system.

**Comment by gnodipac886** [comment]
Also try booting with the invalid config when u update first.
