### ISSUE TITLE
Mute Button 

### ISSUE THREAD

**Issue by Ab2774** [gnodipac886/MatebookXPro-hackintosh#71]
Hey hows going 
I don't have Matebook x pro but I also have this mute button problem, Can you tell me how did fix it?
I have ALC230 layout 20

**Comment by gnodipac886** [comment]
You would need to edit the plist of applealc in xcode. You can take a look at my pull request here: https://github.com/acidanthera/AppleALC/pull/493 for reference.

**Comment by Ab2774** [comment]
Thanks, Really appreciate it
