### ISSUE TITLE
Request NVMeFix

### ISSUE THREAD

**Issue by kvn1351** [gnodipac886/MatebookXPro-hackintosh#72]
Hello @gnodipac886,

first of all, thanks a lot for your work.

I've found out that there is a new lilu plugin to allow for real powermanagement of the NVMe drive. Please add this to your next release. It will improve our battery life a lot perhaps. It needs the newest version of lilu to work. I haven't tested it myself yet.

[https://github.com/acidanthera/NVMeFix](https://github.com/acidanthera/NVMeFix)

**Comment by gnodipac886** [comment]
yep, saw that, will keep in mind!
