### ISSUE TITLE
Installer doesn't finish booting

### ISSUE THREAD

**Issue by oliolioli666** [gnodipac886/MatebookXPro-hackintosh#76]
Hi everyone,

I created the USB, copied die USB-EFI (tried the Clover-file too, and the "makeinstall-only-clover" etc.), but it always stays the same: I choose the USB-Clover-Boot, the apple appears, the bar moves until nearly the end and then a black screen and then the matebook boots into the other OS (Windows or Linux). 

I even tried deleting the main disk as to force some MacOS further booting, but nothing helps. I want this stupid Catalina to run... Redid it all today, formating the stick, freshly installing Windows, nothing helped. Any thoughts?

Best, Oliver

**Comment by kvn1351** [comment]
Did you create your macOS install usb with windows? Try creating one from createinstallmedia from a real mac. A friend of mine had this issue.

**Comment by oliolioli666** [comment]
Windows. I have no Mac available. But isn't that whole gibMacOS meant for creating the usb under Windows? So it runs perfectly fine for the majority expect for your friend and me? :)

Thanks for the fast reply. Seems like I will be stuck with Windows or Linux then. Good night

**Comment by kvn1351** [comment]
> Windows. I have no Mac available. But isn't that whole gibMacOS meant for creating the usb under Windows? So it runs perfectly fine for the majority expect for your friend and me? :)
> 
> Thanks for the fast reply. Seems like I will be stuck with Windows or Linux then. Good night

Well, his problem was that the partition wasn't correctly formated by the script. I don't know the specifics. On Windows you may check if TransMac can see the partition and files.

Also, he simply grabbed an already prepared macOS vmware vm and did it from there. Then it worked perfectly.

**Comment by oliolioli666** [comment]
Thank you! I'll try. Cheers

**Comment by seanfarr788** [comment]
> Thank you! I'll try. Cheers

Were you able to solved this issue?

**Comment by oliolioli666** [comment]
Not at the moment. I was juggling a little with the virtual machine stuff, but I decided to stay on Windows. Energy management is ok, but the speakers are only stereo now... I'm a noob, ;). 

Stay healthy, all the best

**Comment by Roshaanv** [comment]
I have the same problem. Have been trying it for 3 days, but still no solution...

**Comment by Roshaanv** [comment]
@oliolioli666 I had a similar problem. Try this #100

**Comment by oliolioli666** [comment]
It's not crashing, it's just not installing. I will try doing it with MacOS whenever I get my hands in a Mac again. For now I am just gonna enjoy spring... Thank you anyways. All the best
