### ISSUE TITLE
Just a question 

### ISSUE THREAD

**Issue by Edoardo001** [gnodipac886/MatebookXPro-hackintosh#77]
Hi man, I'm working on a similar project (very slow because my life is a mess and have no time) on the Matebook 13. If it is possible, can you tell me the problem in the bluetooth that cause battery drain? Just like you, I've heard around the web that the development of the intel wifi kext are in a good development stage. Have you the git or a forum in which I can see the state of the development or maybe help?

Sorry for my bad English

**Comment by flyinguard** [comment]
hi,the url of intel wifi kext  is: http://bbs.pcbeta.com/viewthread-1838489-1-1.html
