### ISSUE TITLE
Found legacy AptioMemoryFix Driver!

### ISSUE THREAD

**Issue by Kimchi-Coder** [gnodipac886/MatebookXPro-hackintosh#78]
Every time I make a bootable USB and fire it up, this little text appears for a couple seconds and then my screen just goes black. (I'm trying to install Catalina). Not sure what to do.

**Comment by Jay-Russell** [comment]
Deleting OcQuirks.plist and OcQuirks.efi fixed the issue for me. They're both located in the drivers folder.

**Comment by Kimchi-Coder** [comment]
I'll give it a try. Thank you very much!
