### ISSUE TITLE
Can't open macos after closing the lid

### ISSUE THREAD

**Issue by yamyoume** [gnodipac886/MatebookXPro-hackintosh#79]
Can't open macos after closing the lid
I noticed the FN key light is on and the caps lock key light is on and they don't change if I press the keys
however clicking the apple logo and selecting sleep, waiting for that to happen, then closing the lid is totally fine

**Comment by kvn1351** [comment]
You probably haven't run the post install script.

**Comment by yamyoume** [comment]
Wait I thought that script was just to download the repo

**Comment by yamyoume** [comment]
I ran the script now, and it overwrote the clover folder, 
and I knew because i've changed the serial number/machine id 
do you think I should use the serial number/ machine id in the original clover folder from the repo, or should I change it to something else?

**Comment by kvn1351** [comment]
Generate new ones and check them on Apple's website. There are many guide on how to do it.

**Comment by yamyoume** [comment]
Ok thanks 
btw the  closing the lid thing worked it self out , idk how or why
