### ISSUE TITLE
Computer restarts on sleep: sleep transition timed out

### ISSUE THREAD

**Issue by simse** [gnodipac886/MatebookXPro-hackintosh#85]
This is issue is closely related to #31. Unfortunately I am still having the exact same issue. Here's my laptop:
OS: macOS Catalina 10.15.3
Laptop config: i7 + 16GB + MX150
SSD: Crucial MX500 250GB
Wifi dongle: TP-Link AC600

My clover config is the latest from this repo. I have also tried unplugging everything, but even then it would sometimes restart in its sleep. I do not mind not having USB hub functionality if removing a kext could then solve the problem. 

Here's the kernel panic output: https://pastebin.com/a8PruWWV. I suspect the USB ports are to blame, but I am very new to clover and hackintosh, so I'm not sure how I would fix it.

**Comment by kvn1351** [comment]
Try to use OpenCore instead. I haven't had any sleep issues since. There's a OC.zip on another open issue.

**Comment by simse** [comment]
I just tried, and I get a boot fail error. I replaced the clover bootx64.efi with an opencore version, deleted the CLOVER folder and put in the OC folder. What could I be doing wrong?

**Comment by Chatbox1024** [comment]
> Try to use OpenCore instead. I haven't had any sleep issues since. There's a OC.zip on another open issue.

I'm hoping to use OpenCore as well, but rather hopeless as I'm a complete noob at this.  Is there an OpenCore repo out there from a fellow Matebook X Pro user that I can copy from?

**Comment by simse** [comment]
Yeah there's a folder here: https://github.com/gnodipac886/MatebookXPro-hackintosh/issues/75#issuecomment-582215867, but my Matebook X Pro throws a boot fail with that config :/

**Comment by masenov** [comment]
> Yeah there's a folder here: [#75 (comment)](https://github.com/gnodipac886/MatebookXPro-hackintosh/issues/75#issuecomment-582215867), but my Matebook X Pro throws a boot fail with that config :/

Did you figure out how to fix that, I am having the same issue?

**Comment by hatf0** [comment]
@simse @masenov That's my folder- I used it in tandem with Clover prior.

**Comment by Chatbox1024** [comment]
Was this issue fixed?  I see that this is closed.

**Comment by simse** [comment]
Unfortunately this hasn't been fixed. I closed the issue, because I no longer have the Matebook.
