### ISSUE TITLE
Audio Quality Has Degraded with Recent Updates, Headphones Constantly Become Staticy, Output Devices Become Confused

### ISSUE THREAD

**Issue by kmonty** [gnodipac886/MatebookXPro-hackintosh#91]
Been using Matebook X Pro hackintosh for about 16 months. Was previously on Mojave with an older version of this project's Clover setup and made the jump to Catalina (10.15.3) a few weeks ago with the latest code from this repo.

I have noticed that while the laptop speakers perform slightly better, the audio package is substantially less stable and should likely be reverted to the old VoodooHDA setup that this project used before.

Issues I have noticed:
1. After sleep in particular, headphones rarely work as intended, with severely reduced volume (even at top volume) and/or extreme bass/crackling sounds.
2. Looking at the available output devices, it'll often show both as "headphones" when headphones are plugged in. While using the laptop, the output will randomly switch from one headphones to the other, causing sound to stop working.
3. From a fresh reboot, sound performance will occasionally be severely degraded.

The changes to this Clover regarding audio have made sound performance measurably worse. The previous configuration, while it had some drawbacks (not being able to detect headphones being plugged in or not using all 4 laptop speakers, for example), it was extremely stable and dependable.

I recommend reverting these changes until stable audio settings can be introduced.

**Comment by Chatbox1024** [comment]
@kmonty, slightly off topic: Does your 10.15.3 have consistent sleep and wake functionality with no crashes?  I'm trying to resolve the sleep issue that I've been experiencing with my MBXP (i7, 2018).

**Comment by kmonty** [comment]
@Chatbox1024 You should open an issue specific to your issues. That said, I have found sleep to be so unreliable I don't consider it to be a functioning feature of my hackintosh build. I just shut down my laptop whenever would otherwise put it to sleep. I'd say it successfully wakes from sleep maybe 50 to 60 percent of the time. Even when it does wake, it does with degraded audio or other massive battery issues that it's not worth using it.

**Comment by Chatbox1024** [comment]
Regarding the audio, I read through this quick guide: https://www.elitemacx86.com/threads/guide-how-to-enable-audio-on-your-hardware.99/

Then realised that Reset HDA wasn't set, and layout ID wasn't specified in the config.plist (of this repo).

So I went ahead and made the changes.  Seems to be having a stabler audio experience now.  (I'm on AppleALC v1.4.8.
