### ISSUE TITLE
Upgrade bluetooth kext version

### ISSUE THREAD

**Issue by hdamico** [gnodipac886/MatebookXPro-hackintosh#93]
## Description

Currently, the version of the bluetooth kext is outdated, so we should upgrade to the last version, which in my case, gave me system stability.

### TODO

- [x] Download and replace `IntelBluetoothFirmware.kext` and `IntelBluetoothInjector.kext` with their newest version.

**Comment by Chatbox1024** [comment]
Release v1.0.2 is still unstable when it comes to going to sleep on HS05.

**Comment by Chatbox1024** [comment]
Also there's a bug with it when it comes to pairing with the Logitec MX Master 2S.

**Comment by hdamico** [comment]
> Release v1.0.2 is still unstable when it comes to going to sleep on HS05.
> 
> (Are you able to set your system to sleep 50 times consistently without issue?)

I use it on daily basics and at the moment, i didn't get any random reset. Of course it is not stable at all, but, in my case, fixed me the random restarts.

**Comment by hdamico** [comment]
> Also there's a bug with it when it comes to pairing with the Logitec MX Master 2S.

Yeah, i have the same mouse and i am facing the same error, also, i have k780 keyboard and has the same problem.

**Comment by jonescamilla** [comment]
I now have the 1.0.2 version in my kext folder in clover. I am facing no problems connecting my headphones (Jaybird Vista). I am yet to test out how the system responds the the kexts. (Battery, temperature, sleep) I found 1.0.2 [here](https://github.com/zxystd/IntelBluetoothFirmware/releases/tag/1.0.2).
