### ISSUE TITLE
Info Request: Has Anyone Successfully Upgraded to macOS 10.15.4 with This Clover Build?

### ISSUE THREAD

**Issue by kmonty** [gnodipac886/MatebookXPro-hackintosh#97]
As Catalina 10.15.4 was recently released, I am curious if anyone has
1. Successfully updated from 10.15.3 to the recent release?
2. If there were any issues with the update, what were they and how did you get past them?
3. Has the update introduced any _new_ bugs that didn't exist in 15.3?

Thanks!

**Comment by Chatbox1024** [comment]
1. Yes.  Did it just now.  Updated from 10.15.3 to 10.15.4.   Seems to have gone well.
2. No issue so far.
3. Too early to say.

Took about 20 odd minutes to complete, a bit longer than expected, but no errors.  It would reboot twice (IIRC) to complete the process.

**Comment by masenov** [comment]
> 1. Yes.  Did it just now.  Updated from 10.15.3 to 10.15.4.   Seems to have gone well.
> 2. No issue so far.
> 3. Too early to say.
> 
> Took about 20 odd minutes to complete, a bit longer than expected, but no errors. It would reboot twice (IIRC) to complete the process.
> 
> ![image](https://user-images.githubusercontent.com/703217/77497127-cd849280-6e09-11ea-9220-f5d2f98820a3.png)

Do you mind if you post your EFI folder? I can't seem to be able to boot after the update :/

**Comment by masenov** [comment]
nvm managed to fix it by adding the -disablegfxfirmware flag

**Comment by Chatbox1024** [comment]
Odd.  I don't have that boot flag...but it went fine for me.

**Comment by androidek** [comment]
it was quite problematic for me - it crashed around 90%

**Comment by Chatbox1024** [comment]
Were you using the EFI folder from this repo?

**Comment by androidek** [comment]
I also use Windows, but I will try it

**Comment by Chatbox1024** [comment]
Just here to report that the 10.15.4's Supplemental Update went through without issue.

**Comment by kilgil27** [comment]
> nvm managed to fix it by adding the -disablegfxfirmware flag

Where did you add this? I updated to 10.15.4 and can't boot back into clover/os x

**Comment by masenov** [comment]
> > nvm managed to fix it by adding the -disablegfxfirmware flag
> 
> Where did you add this? I updated to 10.15.4 and can't boot back into clover/os x

http://www.macbreaker.com/2015/10/set-boot-flags-arguments-options-clover-unibeast.html?m=1

**Comment by adoster** [comment]
> 
> 
> nvm managed to fix it by adding the -disablegfxfirmware flag

Mine was freezing on boot as well and this fixed it.

**Comment by jonescamilla** [comment]
I've successfully updated my os to 10.15.4. The system would crash at 90% while booting similar to @androidek . The issue was resolved after adding the `-disablegfxfirmware` flag as @masenov mentioned.
